version: '3'
services:
  db:
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile.db
    container_name: indexer_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    container_name: indexer_server
    command: bash -c "uvicorn main:app --host 0.0.0.0 --reload"
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: test_db
      DB_HOST: database
    volumes:
      - ./server:/PageIndexer
    depends_on:
      - db
    links:
      - db:database
    expose:
      - "8000"
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.client
    container_name: indexer_client
    command: "npm start"
    depends_on:
      - backend
    links:
      - backend:server
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./client:/client
      - /client/node_modules
